### ISSUE TITLE
Max Duration in Video Not Working in Gallery

### ISSUE THREAD

**Issue by UrviNivida** [ponnamkarthik/FlutterImageVideoPickerDemo#2]
I have integrated this plugin for video upload in camera option it is working perfectly but when i m selecting video from gallery of 2 min it is selecting it should not be selected , as i have but "maxDuration: Duration(seconds: 30)"  , so please help me

**Comment by ponnamkarthik** [comment]
maxDuration only works when you are picking the video from camera, and that too it only works in few devices 

in android they laucher camera intent to record video but along with maxDuration so it should be supported by that camera to get it work

So i had a project which has the same requirement so this is how i am able to fix it 

https://pub.dev/packages/video_compress

```dart
import 'package:video_compress/video_compress.dart';

// ...
// ...


_checkVideoLength() async {
    try {
      MediaInfo mediaInfo;
      mediaInfo = await VideoCompress.getMediaInfo(widget.videoFile.path);
      Duration d = Duration(microseconds: mediaInfo.duration.toInt());
      if (d.inSeconds > 30) {
        await showDialog<ImageSource>(
            context: context,
            builder: (context) {
              return Dialog(
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10.0),
                ),
                backgroundColor: Colors.white,
                child:  VideoLengthErrorWidget(),
              );
            });
        Navigator.of(context).pop();
      }
    } catch (err) {}
  }
```
